cabinetMedical/urls.py
from . import views
from django.urls import path
app_name='cabinetMedical'
urlpatterns = [
               path('cab/',views.cab,name='cab'), 
               path('cab1/',views.cab1,name='cab1'),
               path('cab2/',views.cab2,name='cab2'),
               path('cab3/',views.cab3,name='cab3'),
               path('cab4/',views.cab4,name='cab4')
            
            ]
               

projetDjango/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cabinetMedical/',include('cabinetMedical.urls',namespace='cabinetMedical'))
]

cabinetMedical/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.fields.related import OneToOneField
from django.db.models import CASCADE
from django.contrib.auth.models import User
class Contact(models.Model):
    nom1=models.CharField(max_length=255,blank=True)
    email1=models.EmailField(max_length=300,blank=True)
    sujet1=models.CharField(max_length=300,blank=True)
    message1=models.TextField(max_length=1000)

class Rdv(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name="rdvs")
    nom2=models.CharField(max_length=255,blank=True)
    email2=models.EmailField(max_length=300,blank=True)
    tel=models.CharField(max_length=300,blank=True)
    date=models.DateField(max_length=1000,blank=True)
    message2=models.TextField(max_length=1000)

class Modifrdv(models.Model):
    nom3=models.CharField(max_length=255,blank=True)
    email3=models.EmailField(max_length=300,blank=True)
    tel1=models.CharField(max_length=300,blank=True)
    date1=models.DateField(max_length=1000,blank=True
    
    )
    message3=models.TextField(max_length=1000)

class Supprdv(models.Model):
    nom4=models.CharField(max_length=255)






# class User(AbstractUser):
#     email = models.EmailField(unique=True)
#     username = None

#     USERNAME_FIELD = 'email'
# Create your models here.

cabinetMedical/forms.py
from typing import Any
from django import forms
from cabinetMedical.models import Contact,Rdv,Modifrdv,Supprdv
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
class Inscription(UserCreationForm):
    username=forms.CharField(label='Nom d utilisateur',widget=forms.TextInput(attrs={'placeholder': 'Votre nom d utilisateur', 'style': 'margin-top:20px;margin-bottom:20;', 'class': 'form-control'}))
    first_name=forms.CharField(label='Nom',widget=forms.TextInput(attrs={'placeholder': 'Votre nom', 'style': 'margin-top:20px;margin-bottom:20;', 'class': 'form-control'}))
    last_name=forms.CharField(label='Prenom',widget=forms.TextInput(attrs={'placeholder': 'Votre prenom', 'style': 'margin-top:20px;margin-bottom:20', 'class': 'form-control'}))
    class Meta(UserCreationForm.Meta):
        model=get_user_model()
        fields=['username','email','first_name','last_name']
    def __init__(self, *args ,**kwargs):
        super(Inscription,self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs['class']='form-control'
        self.fields['password1'].widget.attrs['class']='form-control'
        self.fields['password2'].widget.attrs['class']='form-control'

    

class Connexion(forms.Form):
    nom=forms.CharField(label='Votre nom',widget=forms.TextInput(attrs={'placeholder': 'Votre nom', 'style': 'margin-top:20px;margin-bottom:20;', 'class': 'form-control'}))
    motDePasse=forms.CharField(label='Mot de passe',widget=forms.PasswordInput(attrs={'placeholder': 'Mot de passe', 'style': 'margin-top:20px;margin-bottom:20;', 'class': 'form-control'}))


class ContactForm(forms.ModelForm):
   class Meta:
     model = Contact
     fields = '__all__'
     labels={
        "nom1":"Votre nom",
        "email1":"Votre email",
        "sujet1":"Votre sujet",
        "message1":"votre message",
     }
   #   nom1=forms.CharField(required=False)
     widgets={
        'nom1':forms.TextInput(attrs={ "required":False ,'style': 'width:700px;height:50px;', 'class': 'form-control'}),
        'email1':forms.EmailInput(attrs={ "required":False ,'style': 'width:700px;height:50px;', 'class': 'form-control'}),
        'sujet1':forms.TextInput(attrs={ "required":False ,'style': 'width:700px;height:50px;', 'class': 'form-control'}),
        'message1':forms.TextInput(attrs={ 'style': 'width:700px;height:200px;', 'class': 'form-control'}),
     }
   #  "required":False ,

class RdvForm(forms.ModelForm):
   class Meta:
     model = Rdv
     fields = ["nom2", "email2", "tel", "date","message2"]
     labels={
        "nom2":"Votre nom",
        "email2":"Votre email",
        "tel":"Votre tel",
        "date":"La date du rdv",
        "message2":"votre message",
     }
     widgets={
        'nom2':forms.TextInput(attrs={ "required":False,'style': 'width:700px;height:50px;margin-left: auto;margin-right: auto;', 'class': 'form-control'}),
        'email2':forms.EmailInput(attrs={ "required":False,'style': 'width:700px;height:50px;margin-left: auto;margin-right: auto;', 'class': 'form-control'}),
        'tel':forms.NumberInput(attrs={"required":False, 'style': 'width:700px;height:50px;margin-left: auto;margin-right: auto;', 'class': 'form-control'}),
        'date':forms.DateInput(attrs={ "required":False,'style': 'width:700px;height:50px;margin-left: auto;margin-right: auto;', 'class': 'form-control'}),
        'message2':forms.TextInput(attrs={ 'style': 'width:700px;height:200px;margin-left: auto;margin-right: auto;', 'class': 'form-control'}),
     }


class ModifrdvForm(forms.ModelForm):
   class Meta:
     model = Modifrdv
     fields = '__all__'
     labels={
        "nom3":"Votre nom",
        "email3":"Votre email",
        "tel1":"Votre tel",
        "date1":"La date du rdv",
        "message3":"votre message",
     }
     widgets={
        'nom3':forms.TextInput(attrs={ "required":False,'style': 'width:700px;height:50px;margin-left: auto;margin-right: auto;', 'class': 'form-control'}),
        'email3':forms.EmailInput(attrs={ "required":False,'style': 'width:700px;height:50px;margin-left: auto;margin-right: auto;', 'class': 'form-control'}),
        'tel1':forms.NumberInput(attrs={ "required":False,'style': 'width:700px;height:50px;margin-left: auto;margin-right: auto;', 'class': 'form-control'}),
        'date1':forms.DateInput(attrs={ "required":False,'style': 'width:700px;height:50px;margin-left: auto;margin-right: auto;', 'class': 'form-control'}),
        'message3':forms.TextInput(attrs={ 'style': 'width:700px;height:200px;margin-left: auto;margin-right: auto;', 'class': 'form-control'}),
     }


class SupprdvForm(forms.ModelForm):
   class Meta:
     model = Supprdv
     fields = '__all__'
     labels={
        "nom4":"Votre nom",
     }
     widgets={
        'nom4':forms.TextInput(attrs={ 'style': 'height:50px;width: 50vw; margin-left : 10vw;', 'class': 'form-control'}),
     }


# nom=forms.CharField(label='Votre nom',widget=forms.TextInput(attrs={'placeholder': 'Votre nom', 'style': 'margin-top:20px;margin-bottom:20;', 'class': 'form-control'}))
    # motDePasse=forms.CharField(label='Mot de passe',widget=forms.PasswordInput(attrs={'placeholder': 'Mot de passe', 'style': 'margin-top:20px;margin-bottom:20;', 'class': 'form-control'}))
    # CmotDePasse=forms.CharField(label='Confirmer le mot de passe',widget=forms.PasswordInput(attrs={'placeholder': 'Confirmer le mot de passe', 'style': 'margin-top:20px;margin-bottom:20', 'class': 'form-control'}))
    # def clean(self):
    #     cleaned_data=self.cleaned_data
    #     motDePasse=self.cleaned_data.get("motDePasse")
    #     CmotDePasse=self.cleaned_data.get("CmotDePasse")
    #     if motDePasse != CmotDePasse:
    #         raise forms.ValidationError("Les mots de passe doivent etre identique.")
    #     return cleaned_data







    

cabinetMedical/views.py
from django import forms
from django.shortcuts import render,redirect
from cabinetMedical.forms import Inscription,Connexion
from django.contrib.auth import authenticate,login
from django.conf import settings
from cabinetMedical.forms import ContactForm,RdvForm,ModifrdvForm,SupprdvForm
from django.contrib.auth.models import User
from cabinetMedical.models import Modifrdv,Supprdv,Rdv


# from django.http import HttpResponse
# Create your views here.

# def cab(request):
#     form=Inscription()
#     form2=Connexion()
#     form3=ContactForm()
#     form4=RdvForm()
#     form5=ModifrdvForm()
#     form6=SupprdvForm()
#     # if request.user.is_authenticated:
#     #     x=1
#     nom5= 'xxx'
#     # user1=User()
#     message = ''
#     if request.method == 'POST':
#         form2 = Connexion(request.POST)
#         if form2.is_valid():
#             user = authenticate(
#                 username=form2.cleaned_data['nom'],
#                 password=form2.cleaned_data['motDePasse'],
#             )
#             if user is not None:
#                 login(request, user)
#                 x=1
#                 message = f'Bonjour, {user.username}! Vous êtes connecté.'
#             else:
#                 message = 'Identifiants invalides.'
            
#         form = Inscription(request.POST)
#         if form.is_valid():
#             form.save()		
#             username = form.cleaned_data['username']
#             password = form.cleaned_data['password1']
#             user = authenticate(username=username, password=password)
#             login(request,user)	
#             x=1
#             message = f'Bonjour, {user.username}! Vous êtes connecté.'
#             return redirect('/cabinetMedical/cab')
         
#         form3=ContactForm(request.POST)
#         if form3.is_valid():
#             form3.save()
#             x=1
#             return redirect('/cabinetMedical/cab')
#         form4=RdvForm(request.POST)
#         if form4.is_valid():
#             nom=form4.cleaned_data['nom2']
#             email=form4.cleaned_data['email2']
#             tel1=form4.cleaned_data['tel']
#             date1=form4.cleaned_data['date']
#             message=form4.cleaned_data['message2']
#             rdv=Rdv(user=request.user,nom2=nom,email2=email,tel=tel1,date=date1,message2=message)
#             rdv.save()
#             x=1
#             return redirect('/cabinetMedical/cab')
#         form5=ModifrdvForm(request.POST)
#         if form5.is_valid():
#             nom=form5.cleaned_data['nom3']
#             email=form5.cleaned_data['email3']
#             tel1=form5.cleaned_data['tel1']
#             date1=form5.cleaned_data['date1']
#             message=form5.cleaned_data['message3']
#             up=Rdv.objects.get(user=request.user)
#             up.delete()
#             b=Rdv(user=request.user,nom2=nom,email2=email,tel=tel1,date=date1,message2=message)
#             b.save()
#             x=1
#             return redirect('/cabinetMedical/cab')
#         form6=SupprdvForm(request.POST)
#         if form6.is_valid():
#             nom=form6.cleaned_data['nom4']
#             delet=Rdv.objects.get(user=request.user)
#             delet.delete()
#             x=1
#             return redirect('/cabinetMedical/cab')

#     contexte={
#           "form":form,
#           "form2":form2,
#           "form3":form3,
#           "form4":form4,
#           "form5":form5,
#           "form6":form6,
#           "message":message,
#           "x":x,
#           "nom5":nom5,
#         #   "user1":user1,
        
#     }
#     return render(request,'index1.html',contexte)
    #  return render(request,'index.html',{}) 
    # user=form.save()
    


    # if form.is_valid():
    #         form.save()		
    #         username = form.cleaned_data.get('nom')
    #         password = form.cleaned_data.get('password1')
    #         user = authenticate(username=username, password=password)
    #         login(request,user)	
    #         return redirect(settings.LOGIN_REDIRECT_URL)
def cab(request):
    return render(request,'indexX.html')

def cab2(request):
    form2=Connexion()
    nom5= 'xxx'
    message = ''
    if request.method == 'POST':
        form2 = Connexion(request.POST)
        if form2.is_valid():
            user = authenticate(
                username=form2.cleaned_data['nom'],
                password=form2.cleaned_data['motDePasse'],
            )
            if user is not None:
                login(request, user)
                message = f'Bonjour, {user.username}! Vous êtes connecté.'
            else:
                message = 'Identifiants invalides.'
    contexte={
          "form2":form2,
          "message":message,
          "nom5":nom5,   
    }
    return render(request,'index2.html',contexte)


def cab1(request):
    form=Inscription()
    nom5= 'xxx'
    message = ''
    if request.method == 'POST':
        form = Inscription(request.POST)
        if form.is_valid():
            form.save()		
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request,user)	
            message = f'Bonjour, {user.username}! Vous êtes connecté.'
    contexte={
          "form":form,
          "message":message,
          "nom5":nom5,        
    }
    return render(request,'index1.html',contexte)



def cab3(request):
    form3=ContactForm()
    if request.method == 'POST': 
        form3=ContactForm(request.POST)
        if form3.is_valid():
            form3.save()
    contexte={
          "form3":form3,
        
    }
    return render(request,'index3.html',contexte)




def cab4(request):
    form4=RdvForm()
    if request.method == 'POST':
        form4=RdvForm(request.POST)
        if form4.is_valid():
            nom=form4.cleaned_data['nom2']
            email=form4.cleaned_data['email2']
            tel1=form4.cleaned_data['tel']
            date1=form4.cleaned_data['date']
            message=form4.cleaned_data['message2']
            rdv=Rdv(user=request.user,nom2=nom,email2=email,tel=tel1,date=date1,message2=message)
            rdv.save()
    contexte={
          "form4":form4,
          "message":message,

    }
    return render(request,'index4.html',contexte)

cabinetMedical/templates/index1.html
<!--base.html-->

<!DOCTYPE html>
<html lang="en">

<head>
  
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Dr Hossam Chahi</title>
  <meta content="" name="description">
  <meta content="" name="keywords">
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  <!-- Favicons -->
  <link href="../../static/img/icons8-medical-16.png" rel="icon">
  <link href="../../static/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="../../static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
  <link href="../../static/vendor/animate.css/animate.min.css" rel="stylesheet">
  <link href="../../static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="../../static/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="../../static/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="../../static/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="../../static/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="../../static/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="../../static/css/style.css" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Medilab
  * Updated: Mar 10 2023 with Bootstrap v5.2.3
  * Template URL: https://bootstrapmade.com/medilab-free-medical-bootstrap-theme/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Top Bar ======= -->
  <div id="topbar" class="d-flex align-items-center fixed-top">
    <div class="container d-flex justify-content-between">
      <div class="contact-info d-flex align-items-center">
        <i class="bi bi-envelope"></i> <a href="mailto:contact@example.com">hossamchahi77@gmail.com</a>
        <i class="bi bi-phone"></i> +212687380423
      </div>
      <div class="d-none d-lg-flex social-links align-items-center">
        <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
        <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
        <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
        <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
      </div>
    </div>
  </div>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">

      <h1 class="logo me-auto"><a href="index.html">Docteur Hossam Chahi</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a class="nav-link scrollto active" href="#hero">Accueil</a></li>
          <li><a class="nav-link scrollto" href="#Authentification">Se connecter</a></li>
          <li><a class="nav-link scrollto" href="#about">Qui suis-je</a></li>
          <li><a class="nav-link scrollto" href="#services">Services</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->
    </div>
  </header><!-- End Header -->

  <main id="main">
    
  <!-- ======= Register Section ======= -->
  <section id="Register" class="Register" style="margin:50px 200px 50px 200px;" >
    <div class="section-title">
      <h2>S inscrire</h2> 
    </div>  
    <form method="POST" style="text-align: center;" role="form" >
      {% csrf_token %} 
      {{form}}
      <div style="flex-direction: column">
        <button type="submit" class="btn btn-success" style="margin-top:10px;margin-bottom:20">S inscrire</button>
      </div>
    </form>
  </section>
  <!-- End Register Section -->
    
  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>Cabinet Dr Hossam Chahi</h3>
            <p>
              Residence Louise Thomas et piron <br>
              Boulevard du grand theatre</br>
              Casablanca<br>
              Maroc<br><br>
              <strong>Phone:</strong> +21287380423<br>
              <strong>Email:</strong> hossamchahi77@gmail.com<br>
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="container d-md-flex py-4">

      <div class="me-md-auto text-center text-md-start">
        
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/medilab-free-medical-bootstrap-theme/ -->
          Designed by Hossam Chahi</a>
        </div>
      </div>
      <div class="social-links text-center text-md-right pt-3 pt-md-0">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="../../static/vendor/purecounter/purecounter_vanilla.js"></script>
  <script src="../../static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="../../static/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="../../static/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="../../static/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="../../static/js/main.js"></script>

</body>

</html>

cabinetMedical/templates/index2.html
<!--base.html-->

<!DOCTYPE html>
<html lang="en">

<head>
  
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Dr Hossam Chahi</title>
  <meta content="" name="description">
  <meta content="" name="keywords">
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  <!-- Favicons -->
  <link href="../../static/img/icons8-medical-16.png" rel="icon">
  <link href="../../static/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="../../static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
  <link href="../../static/vendor/animate.css/animate.min.css" rel="stylesheet">
  <link href="../../static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="../../static/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="../../static/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="../../static/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="../../static/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="../../static/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="../../static/css/style.css" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Medilab
  * Updated: Mar 10 2023 with Bootstrap v5.2.3
  * Template URL: https://bootstrapmade.com/medilab-free-medical-bootstrap-theme/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Top Bar ======= -->
  <div id="topbar" class="d-flex align-items-center fixed-top">
    <div class="container d-flex justify-content-between">
      <div class="contact-info d-flex align-items-center">
        <i class="bi bi-envelope"></i> <a href="mailto:contact@example.com">hossamchahi77@gmail.com</a>
        <i class="bi bi-phone"></i> +212687380423
      </div>
      <div class="d-none d-lg-flex social-links align-items-center">
        <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
        <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
        <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
        <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
      </div>
    </div>
  </div>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">

      <h1 class="logo me-auto"><a href="index.html">Docteur Hossam Chahi</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a class="nav-link scrollto active" href="#hero">Accueil</a></li>
          <li><a class="nav-link scrollto" href="#Authentification">Se connecter</a></li>
          <li><a class="nav-link scrollto" href="#about">Qui suis-je</a></li>
          <li><a class="nav-link scrollto" href="#services">Services</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->
      
    </div>
  </header><!-- End Header -->

 <!-- ======= Athentification Section ======= -->
 <section id="Authentification" class="Authentification" style="margin:50px 200px 50px 200px" >
  <div class="section-title">
    <h2>Se connecter</h2>
    <p>Si c est la premiere fois vous devais s inscrire</p>
  </div> 
  <p>{{message}}</p> 
  <form method="POST" role="form" style="text-align: center;"  >
    {% csrf_token %} 
    {{form2}}
    <div style="flex-direction: column">
      <button type="submit" class="btn btn-primary" style="margin-top:10px;margin-bottom:20">Se connecter</button>
      <a href="{% url 'cabinetMedical:cab1' %}" class="btn btn-success" style="margin-top:10px;margin-bottom:20">Creer un nouveau compte</a>
    </div>
  </form>
  
</section >
    
  <!-- ======= Footer ======= -->
  <footer id="footer">

    <div class="footer-top">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>Cabinet Dr Hossam Chahi</h3>
            <p>
              Residence Louise Thomas et piron <br>
              Boulevard du grand theatre</br>
              Casablanca<br>
              Maroc<br><br>
              <strong>Phone:</strong> +21287380423<br>
              <strong>Email:</strong> hossamchahi77@gmail.com<br>
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="container d-md-flex py-4">

      <div class="me-md-auto text-center text-md-start">
        
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/medilab-free-medical-bootstrap-theme/ -->
          Designed by Hossam Chahi</a>
        </div>
      </div>
      <div class="social-links text-center text-md-right pt-3 pt-md-0">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="../../static/vendor/purecounter/purecounter_vanilla.js"></script>
  <script src="../../static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="../../static/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="../../static/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="../../static/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="../../static/js/main.js"></script>

</body>

</html>